/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MarcoNormativoRouteImport } from './routes/marco-normativo'
import { Route as IndexRouteImport } from './routes/index'

const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcoNormativoRoute = MarcoNormativoRouteImport.update({
  id: '/marco-normativo',
  path: '/marco-normativo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marco-normativo': typeof MarcoNormativoRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marco-normativo': typeof MarcoNormativoRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marco-normativo': typeof MarcoNormativoRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/marco-normativo' | '/metodologia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/marco-normativo' | '/metodologia'
  id: '__root__' | '/' | '/marco-normativo' | '/metodologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarcoNormativoRoute: typeof MarcoNormativoRoute
  MetodologiaRoute: typeof MetodologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marco-normativo': {
      id: '/marco-normativo'
      path: '/marco-normativo'
      fullPath: '/marco-normativo'
      preLoaderRoute: typeof MarcoNormativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarcoNormativoRoute: MarcoNormativoRoute,
  MetodologiaRoute: MetodologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
